### ISSUE TITLE
Statistik Motivieren /Polieren 

### ISSUE THREAD

**Issue by Fooo9** [dsiekiera/foe-helfer-extension#1373]
Alle Statistiken am web site unter  Motivieren/Polieren liefern einen mysql Fehler, wie unten gezeigt.
Dies passiert für alle Welten und für alle 4 Statistiken. All Datenuploads sind im foe-helper aktiviert.

Fatal error: Uncaught ADODB_Exception: mysqli error: [1146: Table 'foecre_site3.other_players_service_us1' doesn't exist] in EXECUTE("SELECT DISTINCT YEAR(opse.date_visit) AS Jahr, WEEK(opse.date_visit,1) AS Spalte FROM other_players_service_us1 as ops LEFT JOIN other_players_service_entries_us1 as opse ON ops.ops_id = opse.ops_id WHERE ops.player_id = 185138 AND ops.is_guild_member = 1 AND opse.visitor_action IN ('motivate','polish','polivate_failed') ORDER BY opse.date_visit DESC LIMIT 6 ") in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php:79 Stack trace: #0 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1276): adodb_throw('mysqli', 'EXECUTE', 1146, 'Table 'foecre_s...', 'SELECT DISTINCT...', false, Object(ADODB_mysqli)) #1 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.php(1216): ADOConnection->_Execute('SELECT DISTINCT...') #2 /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb.inc.p in /usr/www/users/foecre/foe-rechner.de/core/3rd-party/adodb/adodb-exceptions.inc.php on line 79

**Comment by Fooo9** [comment]
I've tried using firefox instead of chrome, but the bug remains. All statistics on GB investments, GE progress etc are correctly transferred to foe-rechner.de. But none of the "Motivieren / Polieren" statistics are transferred. Opening any of these statistics on the foe-rechner home page yields the myqsl error shown above. Opening the event history in the game yields a javascript error that can be seen in chrome's and firefox's developer tools console.

I wonder whether deleting my account on foe-rechner.de and re-registering would help. But I can't find an option to delete the account and can't register a new account with the same player id.

This what the javascript error looks like in chrome:
```
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
Promise.then (async)		
(anonymous)	@	_main.js?v=2.5.2.0:1262
Promise.then (async)		
send2Server	@	_main.js?v=2.5.2.0:1258
OtherPlayersMotivation	@	_main.js?v=2.5.2.0:1726
....
